export const endpoints = {
  register: '/auth/register',
  login: '/auth/login',
  resendCode: '/auth/email/otp/resend',
  verifyEmail: '/auth/email/otp/verify',
  verifyTwoFactor: '/auth/2fa/verify',
  forgotPassword: '/auth/password/forgot',
  resetPassword: '/auth/password/reset',
  refresh: '/auth/refresh',
  googleExchange: '/auth/oauth/google',
  currentUser: '/auth/me',
  userBasics: '/users/me',
  profileImage: '/users/me/profile-image',
  profileImageUploadUrl: '/users/me/profile-image/upload-url',
  profileImageComplete: '/users/me/profile-image/upload-complete',
  teacherProfile: '/instructors',
  schoolProfile: '/institutions',
  individualProfile: '/recruiters',
  teacherMe: '/instructors/me',
  schoolMe: '/institutions/me',
  individualMe: '/recruiters/me',
  requirements: '/document-requirements/profile',
  documents: '/documents',
  jobs: '/jobs',
  jobsMine: '/jobs/mine',
  matchingRecommendedJobs: '/matching/jobs/recommended',
  matchingJobs: '/matching/jobs',
  twoFactorStatus: '/auth/2fa/status',
  twoFactorSetup: '/auth/2fa/setup',
  twoFactorEnable: '/auth/2fa/enable',
  twoFactorRecoveryCodes: '/auth/2fa/recovery-codes',
  twoFactorDisable: '/auth/2fa/disable',
};

