import { StyleSheet } from 'react-native';
import { colors, serif } from '../Ui/theme';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#ffffff' },
  topBar: { minHeight: 54, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: colors.border },
  brand: { fontSize: 20, fontWeight: '700', color: colors.ink },
  brandBlue: { color: colors.blue },
  userArea: { flexDirection: 'row', alignItems: 'center', gap: 6, position: 'relative' },
  userEmail: { maxWidth: 110, color: colors.muted, fontSize: 11 },
  avatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.paleBlue, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#006b93', fontWeight: '700', fontSize: 12 },
  profileButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 8, borderRadius: 22, borderWidth: 1, borderColor: colors.border, backgroundColor: '#ffffff' },
  profileMenu: { position: 'absolute', right: 0, top: 48, zIndex: 20, width: 210, padding: 8, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: '#ffffff', shadowColor: '#000000', shadowOpacity: 0.12, shadowRadius: 10, elevation: 6 },
  profileMenuItem: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, borderRadius: 10 },
  profileMenuText: { color: colors.ink, fontSize: 13, fontWeight: '600' },
  scroll: { flex: 1 },
  page: { padding: 16, paddingBottom: 28, gap: 24 },
  title: { fontFamily: serif, fontSize: 30, fontWeight: '700', color: colors.ink },
  subtitle: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  eyebrow: { color: colors.ink, fontSize: 11, fontWeight: '700', letterSpacing: 1.3 },
  section: { gap: 12 },
  topActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  metric: { width: '48%', minHeight: 108, padding: 15, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: '#ffffff', gap: 5 },
  metricFull: { width: '100%' },
  metricValue: { fontFamily: serif, fontWeight: '700', fontSize: 25, color: colors.ink },
  metricLabel: { fontSize: 10, letterSpacing: 1, fontWeight: '700', color: colors.muted },
  metricDetail: { fontSize: 11, color: '#006b93', fontWeight: '600' },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  filters: { flexDirection: 'row', gap: 7, paddingVertical: 2 },
  filter: { borderRadius: 20, paddingHorizontal: 13, paddingVertical: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: '#ffffff' },
  filterActive: { borderColor: colors.blue, backgroundColor: colors.paleBlue },
  filterText: { fontSize: 12, color: colors.muted },
  filterTextActive: { color: '#006b93', fontWeight: '700' },
  card: { borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 16, backgroundColor: '#ffffff', gap: 10 },
  emptyCard: { minHeight: 170, alignItems: 'center', justifyContent: 'center', gap: 10 },
  cardTitle: { fontFamily: serif, fontWeight: '700', fontSize: 22, color: colors.ink },
  cardBody: { fontSize: 13, color: colors.muted, lineHeight: 20 },
  centerText: { textAlign: 'center' },
  teacherTop: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  initials: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  initialsText: { color: '#006b93', fontWeight: '700', fontSize: 12 },
  teacherCopy: { flex: 1, gap: 5 },
  teacherName: { color: colors.ink, fontWeight: '700', fontSize: 15 },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  verified: { borderRadius: 8, backgroundColor: '#effbf2', paddingHorizontal: 7, paddingVertical: 3 },
  verifiedText: { color: '#198742', fontSize: 9, fontWeight: '700', letterSpacing: 0.5 },
  qts: { borderRadius: 8, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 7, paddingVertical: 3 },
  qtsText: { color: colors.muted, fontSize: 9, fontWeight: '700' },
  teacherMeta: { fontSize: 11, color: colors.muted, lineHeight: 17 },
  teacherFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  match: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.paleBlue, alignItems: 'center', justifyContent: 'center' },
  matchText: { fontSize: 11, color: '#006b93', fontWeight: '700' },
  safety: { gap: 9 },
  safetyLabel: { color: '#198742', fontSize: 10, fontWeight: '700', letterSpacing: 0.7 },
  safetyPoint: { color: colors.ink, fontSize: 12, lineHeight: 19 },
  quickButtons: { gap: 8 },
  nav: { flexDirection: 'row', borderTopWidth: 1, borderColor: colors.border, backgroundColor: '#ffffff', paddingTop: 6, paddingBottom: 4 },
  navTab: { flex: 1, minHeight: 62, alignItems: 'center', justifyContent: 'center', gap: 3, borderRadius: 12 },
  navSelected: { backgroundColor: colors.paleBlue },
  navIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' },
  navIconSelected: { backgroundColor: '#ffffff' },
  navLabel: { fontSize: 10, color: colors.muted, fontWeight: '600' },
  navLabelSelected: { color: '#006b93' },
});



