import { StyleSheet } from 'react-native';
import { colors } from '../Ui/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f4f6f8',
  },
  topBar: {
    minHeight: 60,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
    zIndex: 10,
  },
  brand: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.ink,
  },
  brandBlue: {
    color: colors.blue,
  },
  userArea: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    position: 'relative',
  },
  userEmail: {
    maxWidth: 140,
    color: colors.muted,
    fontSize: 12,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  avatarText: {
    color: '#006b93',
    fontWeight: '800',
    fontSize: 12,
  },
  profileButton: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
  },
  profileMenu: {
    position: 'absolute',
    right: 0,
    top: 48,
    zIndex: 20,
    width: 210,
    padding: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
  },
  profileMenuItem: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  profileMenuText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  scroll: {
    flex: 1,
  },
  page: {
    width: '100%',
    maxWidth: 1120,
    alignSelf: 'center',
    padding: 16,
    paddingBottom: 32,
    gap: 22,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.ink,
  },
  subtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  section: {
    gap: 12,
  },
  topActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  metric: {
    width: '48%',
    minHeight: 100,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
    justifyContent: 'space-between',
    gap: 6,
  },
  metricFull: {
    width: '100%',
  },
  metricValue: {
    fontWeight: '800',
    fontSize: 26,
    color: colors.ink,
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.muted,
  },
  metricDetail: {
    fontSize: 11,
    color: '#006b93',
    fontWeight: '700',
  },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  filters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    paddingVertical: 2,
  },
  filter: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
  },
  filterActive: {
    borderColor: colors.blue,
    backgroundColor: colors.paleBlue,
  },
  filterText: {
    fontSize: 12,
    color: colors.muted,
  },
  filterTextActive: {
    color: '#006b93',
    fontWeight: '700',
  },
  card: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 15,
    backgroundColor: '#ffffff',
    gap: 10,
  },
  emptyCard: {
    minHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  cardTitle: {
    flexShrink: 1,
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 23,
    color: colors.ink,
  },
  cardBody: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 20,
  },
  centerText: {
    textAlign: 'center',
  },
  teacherTop: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  initials: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initialsText: {
    color: '#006b93',
    fontWeight: '800',
    fontSize: 12,
  },
  teacherCopy: {
    flex: 1,
    gap: 5,
  },
  teacherName: {
    color: colors.ink,
    fontWeight: '700',
    fontSize: 15,
  },
  badges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  verified: {
    borderRadius: 6,
    backgroundColor: '#effbf2',
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  verifiedText: {
    color: '#198742',
    fontSize: 9,
    fontWeight: '800',
  },
  qts: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  qtsText: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '800',
  },
  teacherMeta: {
    fontSize: 11,
    color: colors.muted,
    lineHeight: 17,
  },
  teacherFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  match: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matchText: {
    fontSize: 11,
    color: '#006b93',
    fontWeight: '800',
  },
  safety: {
    gap: 9,
  },
  safetyLabel: {
    color: '#198742',
    fontSize: 10,
    fontWeight: '800',
  },
  safetyPoint: {
    color: colors.ink,
    fontSize: 12,
    lineHeight: 19,
  },
  quickButtons: {
    gap: 8,
  },
  qrImage: {
    width: 180,
    height: 180,
    alignSelf: 'center',
    borderRadius: 8,
  },
  profileImage: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignSelf: 'center',
    backgroundColor: colors.paleBlue,
  },
  navScroll: {
    flexGrow: 0,
    flexShrink: 0,
    backgroundColor: '#ffffff',
  },
  nav: {
    flexGrow: 1,
    minWidth: '100%',
    minHeight: 66,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
    paddingHorizontal: 6,
    paddingTop: 5,
    paddingBottom: 4,
  },
  navTab: {
    flex: 1,
    minWidth: 80,
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    borderRadius: 6,
  },
  navSelected: {
    backgroundColor: '#eef7fa',
  },
  navIcon: {
    width: 28,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconSelected: {
    backgroundColor: '#ffffff',
    borderRadius: 6,
  },
  navLabel: {
    fontSize: 10,
    color: colors.muted,
    fontWeight: '600',
  },
  navLabelSelected: {
    color: '#006b93',
    fontWeight: '800',
  },
});
