import { StyleSheet } from 'react-native';
import { colors } from '../Ui/theme';

export const limitedProfileStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(5, 12, 17, 0.58)',
  },
  sheet: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '84%',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 12,
  },
  scroll: { padding: 20, gap: 16 },
  close: {
    position: 'absolute',
    zIndex: 2,
    right: 12,
    top: 12,
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hero: { alignItems: 'center', gap: 8, paddingTop: 8 },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.paleBlue,
  },
  avatarEmpty: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initials: { color: '#006b93', fontSize: 25, fontWeight: '700' },
  title: {
    color: colors.ink,
    fontSize: 26,
    fontWeight: '700',
    textAlign: 'center',
  },
  subtitle: { color: colors.muted, fontSize: 12, textAlign: 'center' },
  badge: {
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: '#edf9f1',
  },
  badgeText: { color: '#17783b', fontSize: 10, fontWeight: '800' },
  section: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 14,
    gap: 8,
  },
  label: { color: colors.muted, fontSize: 9, fontWeight: '800' },
  body: { color: colors.ink, fontSize: 13, lineHeight: 21 },
  location: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  tag: {
    borderRadius: 6,
    backgroundColor: colors.soft,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  tagText: { color: colors.ink, fontSize: 11, fontWeight: '600' },
  loading: {
    minHeight: 250,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  error: {
    color: '#b4233f',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
});
