import { StyleSheet } from 'react-native';
import { colors } from '../Ui/theme';

export const securityStyles = StyleSheet.create({
  page: {
    padding: 18,
    paddingBottom: 36,
    gap: 16,
    maxWidth: 1050,
    width: '100%',
    alignSelf: 'center',
  },
  heading: { gap: 4 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '700' },
  subtitle: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  layout: { gap: 14 },
  wideLayout: { flexDirection: 'row', alignItems: 'flex-start' },
  main: { flex: 1, gap: 14 },
  aside: { gap: 14 },
  wideAside: { width: 260 },
  card: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    padding: 16,
    gap: 14,
  },
  cardHead: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  icon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headCopy: { flex: 1, gap: 2 },
  cardTitle: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  body: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  notice: { borderRadius: 7, backgroundColor: colors.soft, padding: 12 },
  noticeText: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  setupRow: { gap: 15 },
  wideSetupRow: { flexDirection: 'row', alignItems: 'center' },
  qrWrap: {
    width: 190,
    height: 190,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
  },
  qr: { width: '100%', height: '100%' },
  setupFields: { flex: 1, gap: 12 },
  secret: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 7,
    padding: 11,
    color: colors.ink,
    fontSize: 11,
  },
  count: { borderRadius: 8, backgroundColor: colors.soft, padding: 14, gap: 3 },
  countLabel: { color: colors.muted, fontSize: 9, fontWeight: '800' },
  countValue: { color: colors.ink, fontSize: 25, fontWeight: '700' },
  codes: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  code: {
    width: '48%',
    borderRadius: 7,
    backgroundColor: colors.soft,
    padding: 10,
    color: colors.ink,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  error: { color: '#b4233f', fontSize: 12 },
});
