import { StyleSheet } from 'react-native';
import { colors } from '../Ui/theme';

export const settingsStyles = StyleSheet.create({
  page: {
    padding: 18,
    paddingBottom: 36,
    gap: 16,
    maxWidth: 1120,
    width: '100%',
    alignSelf: 'center',
  },
  heading: { gap: 4, paddingVertical: 4 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '700' },
  subtitle: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  layout: { gap: 14 },
  wideLayout: { flexDirection: 'row', alignItems: 'flex-start' },
  main: { flex: 1, gap: 14 },
  aside: { gap: 14 },
  wideAside: { width: 260 },
  card: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    padding: 16,
    gap: 14,
  },
  cardHead: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  icon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.paleBlue,
  },
  cardCopy: { flex: 1, gap: 2 },
  cardTitle: { color: colors.ink, fontSize: 12, fontWeight: '800' },
  cardNote: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  imageRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  imageEditor: { width: 52, height: 52 },
  image: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.soft,
  },
  imageEmpty: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageAction: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#ffffff',
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageCopy: { flex: 1, gap: 3 },
  imageTitle: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  imageNote: { color: colors.muted, fontSize: 10, lineHeight: 15 },
  section: { gap: 12 },
  row: { gap: 12 },
  wideRow: { flexDirection: 'row', alignItems: 'flex-start' },
  field: { flex: 1 },
  record: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 7,
    backgroundColor: colors.soft,
    padding: 11,
    gap: 3,
  },
  recordLabel: { color: colors.muted, fontSize: 9, fontWeight: '800' },
  recordValue: { color: colors.ink, fontSize: 12, fontWeight: '600' },
  success: { color: '#17783b', fontSize: 12, fontWeight: '600' },
  error: { color: '#b4233f', fontSize: 12 },
  actions: { gap: 9 },
});
